version: '3.8'

services:
  search_scrape:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SEARCH__SEARXNG_BASE_URL=${SEARCH__SEARXNG_BASE_URL}
    ports:
      - "3400:8000"
    networks:
      - searxng
    volumes:
      - ./crawl4ai:/root/.crawl4ai

networks:
  searxng:
    external: true