version: '3.8'

services:
  hcx_lobechat_plugins:
    container_name: hcx_lobechat_plugins
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SEARCH__SEARXNG_BASE_URL=${SEARCH__SEARXNG_BASE_URL}
    env_file:
      - .env
    ports:
      - "3400:3400"
    networks:
      - searxng
      - lobechat
    volumes:
      - ./crawl4ai:/root/.crawl4ai

networks:
  searxng:
    external: true
  lobechat:
    external: true